### ISSUE TITLE
deploying the app on heroku

### ISSUE THREAD

**Issue by lukemt** [abhshkdz/HackFlowy#24]
tried to deploy the app on heroku via the provided link in order to try the app. here is what happened (I clipped the result to evernote): https://www.evernote.com/shard/s126/sh/b8c07c87-7a29-4b13-9812-a32e27f6b5dc/bfbe02f00c9c7d6da4d82d08f975cae7
any ideas what's happening?

**Comment by desyncr** [comment]
I think you have to enable SSL connection to your database on your connection string. See [here](http://stackoverflow.com/questions/10279965/authentication-error-when-connecting-to-heroku-postgresql-database) and [here](http://stackoverflow.com/questions/31422305/strongloop-heroku-postgres-setup-ssl-error).

**Comment by lukemt** [comment]
hi, i gave it another try. I created an empty db in my heroku account. Tried again, and some other error appeared. after pushing the deploy on heroku half a dozen times it suddenly worked :) 
Might have been a temporary issue of heroku.

**Comment by desyncr** [comment]
We have seen heroku's hiccups here and there.

Please keep in mind that HackFlowy is in development and there is a lot of functionality missing and others that need some love. So, if you're a developer or have a bit of time to give, don't hesitate and join us at [Gitter](https://gitter.im/abhshkdz/HackFlowy) or raise an [issue](https://github.com/abhshkdz/HackFlowy/issues), send a [pull-request](https://github.com/abhshkdz/HackFlowy/pulls).

I'm closing this as it's an Heroku hiccup. Have a nice day.

**Comment by lukemt** [comment]
thanks @desyncr !

**Comment by lukemt** [comment]
just read the bitter comments... I used the european region when trying the first time

**Comment by desyncr** [comment]
We may add a note saying: "Remember to choose US region when prompted."

**Comment by lukemt** [comment]
yes. #25
